Updated database reader.
When trying to run in terminal, error:
Error: Unable to read file: inventory.dat

But, inventory.dat is part of the write process. Therefore, not a cause of alarm.